package preset

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// header is the preamble of every dist/ file. %[1]d is the tier in GB,
// %[2]02d the zero-padded tier, %[3].0f the headroom, %[4]s the setup table.
const header = `version = 1

; llama.cpp router preset - %[1]d GB VRAM
;
; GENERATED by src/cmd/llamapreset - do not edit.
; Edit configs/<provider>/<model>.ini and re-run: go -C src run ./cmd/llamapreset build
;
;   llama-server --models-dir /path/to/models \
;                --models-preset dist/vram-%02[2]dgb.ini \
;                --host 127.0.0.1 --port 8080
;
; Every section name encodes the whole choice:
;
;   <model>-<quant>-<context>-<kv cache type>
;
; A section applies to the subdirectory of --models-dir whose name is exactly
; that. So pick a line from the table, download that quant into a directory
; named after it, and the context and KV cache settings come with it. No paths
; appear in this file. See README.md.
;
; Each model is listed once per distinct setup that fits in %[1]d GB. The
; profile column says what a setup is best at:
;
;   quality   lossless KV cache, best quantisation, then as much context as fits
;   balanced  q8_0 KV cache, at least 64K context, then the best quantisation
;   context   most context first, trading KV cache precision down to q4_0
;
; Profiles that chose the same setup share one line. Figures are gguf-parser
; estimates with flash-attn on and full GPU offload, reserving %.0[3]f GiB for
; the OS/display.
;
; Only sections matching a directory you actually have will work. Requesting
; any other one stalls the client until it gives up, so delete the rest.
;
%[4]s;

[*]
stop-timeout = 30
cache-prompt = true
jinja = true
flash-attn = auto
reasoning-format = auto
`

func DistPath(root string, tierGB int) string {
	return filepath.Join(root, "dist", fmt.Sprintf("vram-%02dgb.ini", tierGB))
}

// RenderTier builds one dist/vram-NNgb.ini.
func RenderTier(t *Tier) string {
	width := 0
	for _, e := range t.Entries {
		if len(e.Name) > width {
			width = len(e.Name)
		}
	}
	var table strings.Builder
	for _, e := range t.Entries {
		fmt.Fprintf(&table, ";   %-*s  %-24s  %5.1f GiB\n",
			width, e.Name, strings.Join(e.Profiles, "+"), e.GiB)
	}

	parts := []string{fmt.Sprintf(header, t.GB, t.GB, HeadroomGiB, table.String())}

	described := ""
	for _, e := range t.Entries {
		parts = append(parts, "")
		if e.ID != described { // entries are grouped by model
			parts = append(parts, e.Doc...)
			described = e.ID
		}
		parts = append(parts, fmt.Sprintf("; %s: %s, %d context, %s KV cache (~%.1f GiB)",
			strings.Join(e.Profiles, " + "), e.Quant, e.Ctx, e.KV, e.GiB))
		parts = append(parts,
			"["+e.Name+"]",
			fmt.Sprintf("ctx-size = %d", e.Ctx),
			"cache-type-k = "+e.KV,
			"cache-type-v = "+e.KV,
		)
		parts = append(parts, e.Body[1:]...) // Body[0] is the config's own [section] line
	}
	return strings.Join(parts, "\n") + "\n"
}

func WriteDist(root string, tiers []*Tier) error {
	if err := os.MkdirAll(filepath.Join(root, "dist"), 0o755); err != nil {
		return err
	}
	for _, t := range tiers {
		if err := os.WriteFile(DistPath(root, t.GB), []byte(RenderTier(t)), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// RenderNotes is the GitHub release body.
func RenderNotes(tiers []*Tier, est *Estimates) string {
	lines := []string{
		"Ready-to-use llama.cpp router presets, one file per VRAM budget.",
		"",
		"Download the one matching your GPU, then start the server:",
		"",
		"```sh",
		`llama-server --models-dir /path/to/models \`,
		`             --models-preset vram-16gb.ini \`,
		"             --host 127.0.0.1 --port 8080",
		"```",
		"",
		"Weight quantisation, context length and KV cache precision all compete for the same",
		"VRAM. Each file offers three ways to spend it, side by side:",
		"",
		"| Profile | Strategy |",
		"| --- | --- |",
	}
	for _, p := range Profiles {
		lines = append(lines, fmt.Sprintf("| `%s` | %s |", p.Name, p.Blurb))
	}
	lines = append(lines,
		"",
		"Sections are named `<model>-<quant>-<context>-<kv>`, and a section applies to the",
		"`--models-dir` subdirectory with exactly that name. Pick a line, download that quant",
		"into a directory named after it, and the rest of the settings come with it. See the",
		"README for the required layout.",
		"",
		"## Contents",
		"",
		"| File | Models | Setups |",
		"| --- | --- | --- |",
	)
	for _, t := range tiers {
		lines = append(lines, fmt.Sprintf("| `vram-%02dgb.ini` | %d | %d |",
			t.GB, t.ModelCount(), len(t.Entries)))
	}

	lines = append(lines, "", "## What each file contains", "")
	for _, t := range tiers {
		lines = append(lines,
			fmt.Sprintf("<details><summary><code>vram-%02dgb.ini</code> &mdash; %d models, %d setups</summary>",
				t.GB, t.ModelCount(), len(t.Entries)),
			"",
			"| Section / directory name | Profiles | Quant | Context | KV cache | Est. VRAM |",
			"| --- | --- | --- | --- | --- | --- |",
		)
		for _, e := range t.Entries {
			lines = append(lines, fmt.Sprintf("| `%s` | %s | `%s` | %s | `%s` | %.1f GiB |",
				e.Name, strings.Join(e.Profiles, ", "), e.Quant, FmtCtx(e.Ctx), e.KV, e.GiB))
		}
		lines = append(lines, "", "</details>", "")
	}

	lines = append(lines,
		"---", "",
		fmt.Sprintf("VRAM measured with %s, flash-attention on, full GPU offload. "+
			"Every setup reserves %.0f GiB for the OS/display.", est.MetaString("tool"), HeadroomGiB),
	)
	return strings.Join(lines, "\n")
}

// placement is where one model appears: tier -> the setups offered at that tier.
type placement struct {
	tiers   []int
	byTier  map[int][]*Setup
	present bool
}

func placements(tiers []*Tier) map[string]*placement {
	out := map[string]*placement{}
	for _, t := range tiers {
		for _, e := range t.Entries {
			p, ok := out[e.ID]
			if !ok {
				p = &placement{byTier: map[int][]*Setup{}, present: true}
				out[e.ID] = p
			}
			if _, seen := p.byTier[t.GB]; !seen {
				p.tiers = append(p.tiers, t.GB)
			}
			p.byTier[t.GB] = append(p.byTier[t.GB], e)
		}
	}
	for _, p := range out {
		sort.Ints(p.tiers)
	}
	return out
}

// RenderModelsMD is the browsable catalogue: what exists, and what each card gets.
func RenderModelsMD(tiers []*Tier, models []*ModelConfig) string {
	where := placements(tiers)

	sorted := append([]*ModelConfig(nil), models...)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	lines := []string{
		"# Model catalogue",
		"",
		"GENERATED by `src/cmd/llamapreset` - do not edit.",
		"",
		fmt.Sprintf("%d models. Use this to find a model, check it fits your card, and see", len(models)),
		"which quantisation and context you get. See the [README](README.md) to get started.",
		"",
		"## All models",
		"",
		"`Smallest card` is the least VRAM that runs the model at all. `Best context` is the",
		"most context any setup reaches on a 32 GB card.",
		"",
		"| Model | Params | Good at | Smallest card | Best context |",
		"| --- | --- | --- | --- | --- |",
	}
	for _, cfg := range sorted {
		p, ok := where[cfg.ID]
		if !ok {
			continue
		}
		largest := p.tiers[len(p.tiers)-1]
		best := 0
		for _, e := range p.byTier[largest] {
			if e.Ctx > best {
				best = e.Ctx
			}
		}
		tags := strings.Join(cfg.Tags, ", ")
		if tags == "" {
			tags = "text"
		}
		lines = append(lines, fmt.Sprintf("| [`%s`](#%s) | %s | %s | %d GB | %s |",
			cfg.ID, strings.ReplaceAll(cfg.ID, ".", ""), cfg.Params, tags, p.tiers[0], FmtCtx(best)))
	}

	lines = append(lines,
		"",
		"## What each card gets",
		"",
		"`Directory name` is what the model's folder under `--models-dir` must be called, and",
		"it is the section name in the preset. Download the quant in the `Quant` column into a",
		"directory with that name.",
		"",
	)
	for _, cfg := range sorted {
		p, ok := where[cfg.ID]
		if !ok {
			continue
		}
		lines = append(lines,
			"### "+cfg.ID,
			"",
			cfg.Title,
			"",
			"| Card | Profiles | Quant | Directory name | VRAM |",
			"| --- | --- | --- | --- | --- |",
		)
		for _, tierGB := range p.tiers {
			for _, e := range p.byTier[tierGB] {
				lines = append(lines, fmt.Sprintf("| %d GB | %s | `%s` | `%s` | %.1f GiB |",
					tierGB, strings.Join(e.Profiles, ", "), e.Quant, e.Name, e.GiB))
			}
		}
		lines = append(lines, "")
	}
	return strings.Join(lines, "\n") + "\n"
}
