; Phi-4 Reasoning 14B
; repo: unsloth/Phi-4-reasoning-GGUF
; docs: https://unsloth.ai/docs/models/tutorials/phi-4-reasoning-how-to-run-and-fine-tune
; params: 14B
; tags: reasoning

[phi-4-reasoning]
n-gpu-layers = 99
reasoning = on
temp = 0.8
top-p = 0.95
min-p = 0.0
