#!/usr/bin/env python3
"""Generate llama.cpp router presets, one file per VRAM tier and profile.

llama.cpp's preset format has no include directive (see common/preset.cpp:
parse_ini_from_file accepts only header / key=value / comment / blank lines),
so tier files are generated by concatenation rather than composed at runtime.

Quantisation and context are chosen together, because they compete for the same
VRAM. Three profiles spend the budget differently:

  quality   best quant first, then as much context as fits
  balanced  at least 64K context, then the best quant, then more context
  context   most context first, then the best quant that still fits

Sources:
  configs/<provider>/<model>.ini  one section per model, tuning only, no paths
  configs/vram-estimates.json     gguf-parser measurements

Output:
  dist/vram-<NN>gb-<profile>.ini

Usage:
    python3 src/build.py            # write dist/
    python3 src/build.py --notes    # print release notes to stdout
"""

import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONFIGS = ROOT / "configs"
DIST = ROOT / "dist"

TIERS = [4, 8, 16, 24, 32]
HEADROOM_GIB = 1.0     # left free for the OS / display
MIN_CTX = 4096         # below this a model is not worth shipping
BALANCED_CTX = 65536   # what the balanced profile tries to reach first

PROFILES = {
    "quality":  "best quantisation first, then as much context as fits",
    "balanced": "at least 64K context, then the best quantisation, then more context",
    "context":  "most context first, then the best quantisation that still fits",
}

HEADER = """version = 1

; llama.cpp router preset - {tier} GB VRAM, {profile} profile
;
; {blurb}
;
; GENERATED by src/build.py - do not edit.
; Edit configs/<provider>/<model>.ini and re-run: python3 src/build.py
;
; Models are located by --models-dir. Each section name must exactly match a
; subdirectory under that root; no paths appear in this file. See README.md.
;
;   llama-server --models-dir /path/to/models \\
;                --models-preset dist/vram-{tier:02d}gb-{profile}.ini \\
;                --host 127.0.0.1 --port 8080
;
; Download the quant listed below into the matching directory. Figures are
; gguf-parser estimates with flash-attn on, q8_0 K/V cache and full GPU
; offload, reserving {headroom:.0f} GiB for the OS/display.
;
; A model you have not downloaded still appears here. Requesting it stalls the
; client until it gives up, so delete sections you do not intend to use.
;
{table};

[*]
stop-timeout = 30
cache-prompt = true
jinja = true
flash-attn = auto
cache-type-k = q8_0
cache-type-v = q8_0
reasoning-format = auto
"""


def load_model_configs():
    """[(provider, model_id, body_lines, doc_lines, ctx_cap)] sorted by path."""
    out = []
    for path in sorted(CONFIGS.rglob("*.ini")):
        text = path.read_text()
        m = re.search(r"^\[([^\]]+)\]", text, re.M)
        if not m:
            sys.exit(f"{path}: no [section] found")
        model_id = m.group(1).strip()
        doc = [l for l in text[: m.start()].splitlines() if l.strip().startswith(";")]

        cap = None
        body = []
        for line in text[m.start():].rstrip().splitlines():
            key = line.split("=", 1)[0].strip() if "=" in line else ""
            if key == "ctx-size":
                # A config may cap context; build.py never exceeds it.
                cap = int(line.split("=", 1)[1].strip())
                continue
            body.append(line)
        out.append((path.parent.name, model_id, body, doc, cap))
    return out


def vram(data, quant, ctx):
    """VRAM of a quant at a measured context size.

    KV cost per token does not depend on the weight quant, so every quant's
    curve is the reference curve shifted by a constant.
    """
    return data["ref_curve"][str(ctx)] + data["quants"][quant] - data["quants"][data["ref_quant"]]


def candidates(data, budget, cap):
    """[(quant, ctx, gib)] that fit, ordered worst-to-best quant."""
    ladder = sorted(int(c) for c in data["ref_curve"])
    if cap:
        ladder = [c for c in ladder if c <= cap]
    order = sorted(data["quants"], key=lambda q: data["quants"][q])  # cheap -> best
    out = []
    for quant in order:
        for ctx in ladder:
            if ctx < MIN_CTX and ctx != ladder[-1]:
                continue
            gib = vram(data, quant, ctx)
            if gib <= budget:
                out.append((quant, ctx, gib))
    return out


def pick(data, budget, profile, cap):
    """Choose (quant, ctx, gib) for a profile, or None if nothing fits."""
    opts = candidates(data, budget, cap)
    if not opts:
        return None
    rank = {q: i for i, q in enumerate(sorted(data["quants"], key=lambda q: data["quants"][q]))}

    if profile == "quality":
        return max(opts, key=lambda o: (rank[o[0]], o[1]))
    if profile == "context":
        return max(opts, key=lambda o: (o[1], rank[o[0]]))

    # balanced: reach the target context first, then buy quality with the rest
    target = min(BALANCED_CTX, max(o[1] for o in opts))
    good = [o for o in opts if o[1] >= target]
    if good:
        best_quant = max(rank[o[0]] for o in good)
        same = [o for o in good if rank[o[0]] == best_quant]
        return max(same, key=lambda o: o[1])
    return max(opts, key=lambda o: (o[1], rank[o[0]]))


def plan(est, models):
    """{(tier, profile): [(provider, model_id, quant, ctx, gib, body, doc)]}"""
    out = {}
    for tier in TIERS:
        budget = tier - HEADROOM_GIB
        for profile in PROFILES:
            chosen = []
            for provider, model_id, body, doc, cap in models:
                got = pick(est["models"][model_id], budget, profile, cap)
                if got:
                    quant, ctx, gib = got
                    chosen.append((provider, model_id, quant, ctx, gib, body, doc))
            if chosen:
                out[(tier, profile)] = chosen
    return out


def write_dist(built):
    DIST.mkdir(exist_ok=True)
    written = []
    for (tier, profile), chosen in built.items():
        w = max(len(m) for _, m, _, _, _, _, _ in chosen)
        table = "".join(
            f";   {m:<{w}}  {q:<12}  {c:>7} ctx  {g:5.1f} GiB\n"
            for _, m, q, c, g, _, _ in chosen
        )
        parts = [HEADER.format(tier=tier, profile=profile, blurb=PROFILES[profile],
                               headroom=HEADROOM_GIB, table=table)]
        for _, model_id, quant, ctx, gib, body, doc in chosen:
            parts.append("")
            parts.extend(doc)
            parts.append(f"; this profile: {quant}, {ctx} context (~{gib:.1f} GiB)")
            parts.append(body[0])            # the [section] line
            parts.append(f"ctx-size = {ctx}")
            parts.extend(body[1:])
        path = DIST / f"vram-{tier:02d}gb-{profile}.ini"
        path.write_text("\n".join(parts) + "\n")
        written.append((path, len(chosen)))
    return written


def render_notes(built, est):
    meta = est["_meta"]
    lines = [
        "Ready-to-use llama.cpp router presets, grouped by VRAM budget.",
        "",
        "Each budget comes in three profiles, which spend the same VRAM differently:",
        "",
        "| Profile | Strategy |",
        "| --- | --- |",
    ]
    for name, blurb in PROFILES.items():
        lines.append(f"| `{name}` | {blurb} |")
    lines += [
        "",
        "Download the one matching your GPU, then start the server:",
        "",
        "```sh",
        "llama-server --models-dir /path/to/models \\",
        "             --models-preset vram-16gb-balanced.ini \\",
        "             --host 127.0.0.1 --port 8080",
        "```",
        "",
        "Model folder names must match the section names in the file. "
        "See the README for the required layout.",
        "",
        "## Contents",
        "",
        "| Profile | " + " | ".join(f"{t} GB" for t in TIERS) + " |",
        "| --- | " + " | ".join("---" for _ in TIERS) + " |",
    ]
    for profile in PROFILES:
        cells = [str(len(built.get((t, profile), []))) for t in TIERS]
        lines.append(f"| `{profile}` | " + " | ".join(cells) + " |")

    lines += ["", "## Quant and context per profile", ""]
    for (tier, profile), chosen in built.items():
        lines += [
            f"<details><summary><code>vram-{tier:02d}gb-{profile}.ini</code> "
            f"&mdash; {len(chosen)} models</summary>", "",
            "| Model | Quant | Context | Est. VRAM |", "| --- | --- | --- | --- |",
        ]
        for _, model_id, quant, ctx, gib, _, _ in chosen:
            lines.append(f"| `{model_id}` | `{quant}` | {ctx:,} | {gib:.1f} GiB |")
        lines += ["", "</details>", ""]

    lines += [
        "---", "",
        f"VRAM measured with {meta['tool']}, flash-attention on, q8_0 K/V cache, full GPU "
        f"offload. Each profile reserves {HEADROOM_GIB:.0f} GiB for the OS/display.",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--notes", action="store_true",
                    help="print release notes to stdout instead of writing dist/")
    args = ap.parse_args()

    est = json.loads((CONFIGS / "vram-estimates.json").read_text())
    models = load_model_configs()

    incomplete = [m for _, m, _, _, _ in models
                  if not est["models"].get(m, {}).get("ref_curve")
                  or not est["models"].get(m, {}).get("quants")]
    if incomplete:
        sys.exit("no measurements for: " + ", ".join(incomplete)
                 + "\nrun: python3 src/measure.py --missing")

    built = plan(est, models)

    if args.notes:
        print(render_notes(built, est))
        return

    for path, n in write_dist(built):
        print(f"wrote {path.relative_to(ROOT)}  ({n} models)")


if __name__ == "__main__":
    main()
