#!/usr/bin/env python3
"""Generate per-VRAM-tier llama.cpp router presets.

llama.cpp's preset format has no include directive (see common/preset.cpp:
parse_ini_from_file accepts only header / key=value / comment / blank lines),
so tier files are generated by concatenation rather than composed at runtime.

Sources:
  configs/<provider>/<model>.ini  one section per model, tuning only, no paths
  configs/vram-estimates.json     gguf-parser measurements, quant -> GiB

Output:
  dist/vram-<NN>gb.ini
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONFIGS = ROOT / "configs"
DIST = ROOT / "dist"

TIERS = [4, 8, 16, 24, 32]
HEADROOM_GIB = 1.0  # left free for the OS / display

HEADER = """version = 1

; llama.cpp router preset - {tier} GB VRAM profile
;
; GENERATED by src/build.py - do not edit.
; Edit configs/<provider>/<model>.ini and re-run: python3 src/build.py
;
; Models are located by --models-dir. Each section name must exactly match a
; subdirectory under that root; no paths appear in this file. See README.md.
;
;   llama-server --models-dir /path/to/models \\
;                --models-preset dist/vram-{tier:02d}gb.ini \\
;                --host 127.0.0.1 --port 8080
;
; Download the quant listed below into the matching directory. Figures are
; gguf-parser estimates at ctx-size {ctx}, flash-attn on, q8_0 K/V cache,
; full GPU offload, with {headroom:.0f} GiB reserved for the OS/display.
;
{table};

[*]
stop-timeout = 30
cache-prompt = true
jinja = true
flash-attn = auto
cache-type-k = q8_0
cache-type-v = q8_0
reasoning-format = auto
"""


def load_model_configs():
    """Return [(provider, model_id, body_lines, doc_lines)] sorted by provider/model."""
    out = []
    for path in sorted(CONFIGS.rglob("*.ini")):
        text = path.read_text()
        m = re.search(r"^\[([^\]]+)\]", text, re.M)
        if not m:
            sys.exit(f"{path}: no [section] found")
        model_id = m.group(1).strip()
        doc = [l for l in text[: m.start()].splitlines() if l.strip().startswith(";")]
        body = text[m.start():].rstrip().splitlines()
        out.append((path.parent.name, model_id, body, doc))
    return out


def pick_quant(estimates, budget_gib):
    """Best-quality quant that still fits, or None."""
    fits = {q: v for q, v in estimates.items() if v <= budget_gib}
    if not fits:
        return None, None
    best = max(fits, key=fits.get)
    return best, fits[best]


def main():
    est = json.loads((CONFIGS / "vram-estimates.json").read_text())
    ctx = est["_meta"]["params"]["ctx_size"]
    models = load_model_configs()

    missing = [m for _, m, _, _ in models if m not in est["models"]]
    if missing:
        sys.exit("no VRAM estimates for: " + ", ".join(missing))

    DIST.mkdir(exist_ok=True)
    summary = []

    for tier in TIERS:
        budget = tier - HEADROOM_GIB
        chosen = []
        for provider, model_id, body, doc in models:
            quant, vram = pick_quant(est["models"][model_id], budget)
            if quant:
                chosen.append((provider, model_id, quant, vram, body, doc))

        if not chosen:
            continue

        width = max(len(m) for _, m, _, _, _, _ in chosen)
        table = "".join(
            f";   {m:<{width}}  {q:<12}  {v:5.1f} GiB   ({p})\n"
            for p, m, q, v, _, _ in chosen
        )

        parts = [HEADER.format(tier=tier, ctx=ctx, headroom=HEADROOM_GIB, table=table)]
        for provider, model_id, quant, vram, body, doc in chosen:
            parts.append("")
            parts.extend(doc)
            parts.append(f"; quant for this tier: {quant}  (~{vram:.1f} GiB)")
            parts.extend(body)

        path = DIST / f"vram-{tier:02d}gb.ini"
        path.write_text("\n".join(parts) + "\n")
        summary.append((path, len(chosen)))

    for path, n in summary:
        print(f"wrote {path.relative_to(ROOT)}  ({n} models)")


if __name__ == "__main__":
    main()
